# Generated by Django 5.2.3 on 2025-06-16 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodentry',
            name='food',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='foodentry',
            name='quantity',
            field=models.PositiveIntegerField(help_text='Quantity in grams'),
        ),
        migrations.DeleteModel(
            name='Food',
        ),
    ]
