# Generated by Django 5.2.3 on 2025-06-16 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0002_alter_foodentry_food_alter_foodentry_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='carbohydrates_total_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='fat_total_g',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='foodentry',
            name='protein_g',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
