# Generated by Django 5.2.3 on 2025-06-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_getinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='getinfo',
            name='height_cm',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='getinfo',
            name='weight_kg',
            field=models.PositiveIntegerField(),
        ),
    ]
