# Generated by Django 5.2.3 on 2025-06-18 04:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0005_alter_getinfo_height_cm_alter_getinfo_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='getinfo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
