# Generated by Django 5.2.3 on 2025-06-18 04:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0006_getinfo_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
