# Generated by Django 5.2.3 on 2025-06-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workoutexercise_exercise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(),
        ),
    ]
