# Generated by Django 5.2.3 on 2025-06-16 13:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_alter_workout_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='user',
        ),
        migrations.AddField(
            model_name='workout',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 16, 13, 48, 56, 876337, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workout',
            name='duration',
            field=models.DurationField(help_text='Duration of you workout'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='notes',
            field=models.TextField(blank=True, help_text='Any additional notes'),
        ),
        migrations.CreateModel(
            name='WorkoutExercises',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_name', models.CharField(max_length=100)),
                ('muscle_group', models.CharField(choices=[('chest', 'Chest'), ('back', 'Back'), ('legs', 'Legs'), ('shoulders', 'Shoulders'), ('arms', 'Arms'), ('core', 'Core'), ('full_body', 'Full Body')], max_length=20)),
                ('equipment_used', models.CharField(blank=True, max_length=100)),
                ('sets', models.PositiveIntegerField()),
                ('reps', models.PositiveIntegerField()),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='Weight in kg/lbs', max_digits=6, null=True)),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='workouts.workout')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkoutExercise',
        ),
    ]
